// Generated by delombok at Wed Sep 25 21:26:01 CST 2024
package consign.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.*;

/**
 * @author fdse
 */
@Entity
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(schema = "ts-consign-mysql")
public class ConsignRecord {
    @Id
    @Column(name = "consign_record_id")
    private String id;
    private String orderId;
    @Column(name = "user_id")
    private String accountId;
    private String handleDate;
    private String targetDate;
    @Column(name = "from_place")
    private String from;
    @Column(name = "to_place")
    private String to;
    private String consignee;
    @Column(name = "consign_record_phone")
    private String phone;
    private double weight;
    @Column(name = "consign_record_price")
    private double price;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAccountId() {
        return this.accountId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHandleDate() {
        return this.handleDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTargetDate() {
        return this.targetDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFrom() {
        return this.from;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTo() {
        return this.to;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getConsignee() {
        return this.consignee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public double getWeight() {
        return this.weight;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAccountId(final String accountId) {
        this.accountId = accountId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHandleDate(final String handleDate) {
        this.handleDate = handleDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetDate(final String targetDate) {
        this.targetDate = targetDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFrom(final String from) {
        this.from = from;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTo(final String to) {
        this.to = to;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setConsignee(final String consignee) {
        this.consignee = consignee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeight(final double weight) {
        this.weight = weight;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrice(final double price) {
        this.price = price;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ConsignRecord)) return false;
        final ConsignRecord other = (ConsignRecord) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getWeight(), other.getWeight()) != 0) return false;
        if (java.lang.Double.compare(this.getPrice(), other.getPrice()) != 0) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$orderId = this.getOrderId();
        final java.lang.Object other$orderId = other.getOrderId();
        if (this$orderId == null ? other$orderId != null : !this$orderId.equals(other$orderId)) return false;
        final java.lang.Object this$accountId = this.getAccountId();
        final java.lang.Object other$accountId = other.getAccountId();
        if (this$accountId == null ? other$accountId != null : !this$accountId.equals(other$accountId)) return false;
        final java.lang.Object this$handleDate = this.getHandleDate();
        final java.lang.Object other$handleDate = other.getHandleDate();
        if (this$handleDate == null ? other$handleDate != null : !this$handleDate.equals(other$handleDate)) return false;
        final java.lang.Object this$targetDate = this.getTargetDate();
        final java.lang.Object other$targetDate = other.getTargetDate();
        if (this$targetDate == null ? other$targetDate != null : !this$targetDate.equals(other$targetDate)) return false;
        final java.lang.Object this$from = this.getFrom();
        final java.lang.Object other$from = other.getFrom();
        if (this$from == null ? other$from != null : !this$from.equals(other$from)) return false;
        final java.lang.Object this$to = this.getTo();
        final java.lang.Object other$to = other.getTo();
        if (this$to == null ? other$to != null : !this$to.equals(other$to)) return false;
        final java.lang.Object this$consignee = this.getConsignee();
        final java.lang.Object other$consignee = other.getConsignee();
        if (this$consignee == null ? other$consignee != null : !this$consignee.equals(other$consignee)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ConsignRecord;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $weight = java.lang.Double.doubleToLongBits(this.getWeight());
        result = result * PRIME + (int) ($weight >>> 32 ^ $weight);
        final long $price = java.lang.Double.doubleToLongBits(this.getPrice());
        result = result * PRIME + (int) ($price >>> 32 ^ $price);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $orderId = this.getOrderId();
        result = result * PRIME + ($orderId == null ? 43 : $orderId.hashCode());
        final java.lang.Object $accountId = this.getAccountId();
        result = result * PRIME + ($accountId == null ? 43 : $accountId.hashCode());
        final java.lang.Object $handleDate = this.getHandleDate();
        result = result * PRIME + ($handleDate == null ? 43 : $handleDate.hashCode());
        final java.lang.Object $targetDate = this.getTargetDate();
        result = result * PRIME + ($targetDate == null ? 43 : $targetDate.hashCode());
        final java.lang.Object $from = this.getFrom();
        result = result * PRIME + ($from == null ? 43 : $from.hashCode());
        final java.lang.Object $to = this.getTo();
        result = result * PRIME + ($to == null ? 43 : $to.hashCode());
        final java.lang.Object $consignee = this.getConsignee();
        result = result * PRIME + ($consignee == null ? 43 : $consignee.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ConsignRecord(id=" + this.getId() + ", orderId=" + this.getOrderId() + ", accountId=" + this.getAccountId() + ", handleDate=" + this.getHandleDate() + ", targetDate=" + this.getTargetDate() + ", from=" + this.getFrom() + ", to=" + this.getTo() + ", consignee=" + this.getConsignee() + ", phone=" + this.getPhone() + ", weight=" + this.getWeight() + ", price=" + this.getPrice() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ConsignRecord(final String id, final String orderId, final String accountId, final String handleDate, final String targetDate, final String from, final String to, final String consignee, final String phone, final double weight, final double price) {
        this.id = id;
        this.orderId = orderId;
        this.accountId = accountId;
        this.handleDate = handleDate;
        this.targetDate = targetDate;
        this.from = from;
        this.to = to;
        this.consignee = consignee;
        this.phone = phone;
        this.weight = weight;
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ConsignRecord() {
    }
}
