// Generated by delombok at Wed Sep 25 21:26:01 CST 2024
package consign.entity;

/**
 * @author fdse
 */
public class GetPriceDomain {
    private double weight;
    private boolean isWithinRegion;

    public GetPriceDomain() {
        //Default Constructor
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public double getWeight() {
        return this.weight;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isWithinRegion() {
        return this.isWithinRegion;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeight(final double weight) {
        this.weight = weight;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWithinRegion(final boolean isWithinRegion) {
        this.isWithinRegion = isWithinRegion;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GetPriceDomain)) return false;
        final GetPriceDomain other = (GetPriceDomain) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getWeight(), other.getWeight()) != 0) return false;
        if (this.isWithinRegion() != other.isWithinRegion()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GetPriceDomain;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $weight = java.lang.Double.doubleToLongBits(this.getWeight());
        result = result * PRIME + (int) ($weight >>> 32 ^ $weight);
        result = result * PRIME + (this.isWithinRegion() ? 79 : 97);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "GetPriceDomain(weight=" + this.getWeight() + ", isWithinRegion=" + this.isWithinRegion() + ")";
    }
}
