// Generated by delombok at Wed Sep 25 21:32:07 CST 2024
package food_delivery.entity;

public class DeliveryInfo {
    private String orderId;
    private String deliveryTime;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeliveryTime() {
        return this.deliveryTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryTime(final String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DeliveryInfo)) return false;
        final DeliveryInfo other = (DeliveryInfo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$orderId = this.getOrderId();
        final java.lang.Object other$orderId = other.getOrderId();
        if (this$orderId == null ? other$orderId != null : !this$orderId.equals(other$orderId)) return false;
        final java.lang.Object this$deliveryTime = this.getDeliveryTime();
        final java.lang.Object other$deliveryTime = other.getDeliveryTime();
        if (this$deliveryTime == null ? other$deliveryTime != null : !this$deliveryTime.equals(other$deliveryTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DeliveryInfo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $orderId = this.getOrderId();
        result = result * PRIME + ($orderId == null ? 43 : $orderId.hashCode());
        final java.lang.Object $deliveryTime = this.getDeliveryTime();
        result = result * PRIME + ($deliveryTime == null ? 43 : $deliveryTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DeliveryInfo(orderId=" + this.getOrderId() + ", deliveryTime=" + this.getDeliveryTime() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeliveryInfo() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DeliveryInfo(final String orderId, final String deliveryTime) {
        this.orderId = orderId;
        this.deliveryTime = deliveryTime;
    }
}
