// Generated by delombok at Wed Sep 25 21:32:07 CST 2024
package food_delivery.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.hibernate.annotations.GenericGenerator;
import javax.persistence.*;
import java.util.List;
import edu.fudan.common.entity.Food;

@Entity
@GenericGenerator(name = "jpa-uuid", strategy = "uuid")
@JsonIgnoreProperties(ignoreUnknown = true)
public class FoodDeliveryOrder {
    @Id
    @GeneratedValue(generator = "jpa-uuid")
    @Column(length = 36)
    private String id;
    private String stationFoodStoreId;
    @ElementCollection(targetClass = Food.class)
    private List<Food> foodList;
    private String tripId;
    private int seatNo;
    private String createdTime;
    private String deliveryTime;
    private double deliveryFee;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStationFoodStoreId() {
        return this.stationFoodStoreId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Food> getFoodList() {
        return this.foodList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTripId() {
        return this.tripId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getSeatNo() {
        return this.seatNo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCreatedTime() {
        return this.createdTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeliveryTime() {
        return this.deliveryTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public double getDeliveryFee() {
        return this.deliveryFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStationFoodStoreId(final String stationFoodStoreId) {
        this.stationFoodStoreId = stationFoodStoreId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFoodList(final List<Food> foodList) {
        this.foodList = foodList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTripId(final String tripId) {
        this.tripId = tripId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeatNo(final int seatNo) {
        this.seatNo = seatNo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedTime(final String createdTime) {
        this.createdTime = createdTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryTime(final String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryFee(final double deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FoodDeliveryOrder)) return false;
        final FoodDeliveryOrder other = (FoodDeliveryOrder) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getSeatNo() != other.getSeatNo()) return false;
        if (java.lang.Double.compare(this.getDeliveryFee(), other.getDeliveryFee()) != 0) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$stationFoodStoreId = this.getStationFoodStoreId();
        final java.lang.Object other$stationFoodStoreId = other.getStationFoodStoreId();
        if (this$stationFoodStoreId == null ? other$stationFoodStoreId != null : !this$stationFoodStoreId.equals(other$stationFoodStoreId)) return false;
        final java.lang.Object this$foodList = this.getFoodList();
        final java.lang.Object other$foodList = other.getFoodList();
        if (this$foodList == null ? other$foodList != null : !this$foodList.equals(other$foodList)) return false;
        final java.lang.Object this$tripId = this.getTripId();
        final java.lang.Object other$tripId = other.getTripId();
        if (this$tripId == null ? other$tripId != null : !this$tripId.equals(other$tripId)) return false;
        final java.lang.Object this$createdTime = this.getCreatedTime();
        final java.lang.Object other$createdTime = other.getCreatedTime();
        if (this$createdTime == null ? other$createdTime != null : !this$createdTime.equals(other$createdTime)) return false;
        final java.lang.Object this$deliveryTime = this.getDeliveryTime();
        final java.lang.Object other$deliveryTime = other.getDeliveryTime();
        if (this$deliveryTime == null ? other$deliveryTime != null : !this$deliveryTime.equals(other$deliveryTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FoodDeliveryOrder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getSeatNo();
        final long $deliveryFee = java.lang.Double.doubleToLongBits(this.getDeliveryFee());
        result = result * PRIME + (int) ($deliveryFee >>> 32 ^ $deliveryFee);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $stationFoodStoreId = this.getStationFoodStoreId();
        result = result * PRIME + ($stationFoodStoreId == null ? 43 : $stationFoodStoreId.hashCode());
        final java.lang.Object $foodList = this.getFoodList();
        result = result * PRIME + ($foodList == null ? 43 : $foodList.hashCode());
        final java.lang.Object $tripId = this.getTripId();
        result = result * PRIME + ($tripId == null ? 43 : $tripId.hashCode());
        final java.lang.Object $createdTime = this.getCreatedTime();
        result = result * PRIME + ($createdTime == null ? 43 : $createdTime.hashCode());
        final java.lang.Object $deliveryTime = this.getDeliveryTime();
        result = result * PRIME + ($deliveryTime == null ? 43 : $deliveryTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "FoodDeliveryOrder(id=" + this.getId() + ", stationFoodStoreId=" + this.getStationFoodStoreId() + ", foodList=" + this.getFoodList() + ", tripId=" + this.getTripId() + ", seatNo=" + this.getSeatNo() + ", createdTime=" + this.getCreatedTime() + ", deliveryTime=" + this.getDeliveryTime() + ", deliveryFee=" + this.getDeliveryFee() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FoodDeliveryOrder(final String id, final String stationFoodStoreId, final List<Food> foodList, final String tripId, final int seatNo, final String createdTime, final String deliveryTime, final double deliveryFee) {
        this.id = id;
        this.stationFoodStoreId = stationFoodStoreId;
        this.foodList = foodList;
        this.tripId = tripId;
        this.seatNo = seatNo;
        this.createdTime = createdTime;
        this.deliveryTime = deliveryTime;
        this.deliveryFee = deliveryFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FoodDeliveryOrder() {
    }
}
