// Generated by delombok at Wed Sep 25 21:32:07 CST 2024
package food_delivery.entity;

public class SeatInfo {
    private String orderId;
    private int seatNo;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getSeatNo() {
        return this.seatNo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeatNo(final int seatNo) {
        this.seatNo = seatNo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SeatInfo)) return false;
        final SeatInfo other = (SeatInfo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getSeatNo() != other.getSeatNo()) return false;
        final java.lang.Object this$orderId = this.getOrderId();
        final java.lang.Object other$orderId = other.getOrderId();
        if (this$orderId == null ? other$orderId != null : !this$orderId.equals(other$orderId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SeatInfo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getSeatNo();
        final java.lang.Object $orderId = this.getOrderId();
        result = result * PRIME + ($orderId == null ? 43 : $orderId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "SeatInfo(orderId=" + this.getOrderId() + ", seatNo=" + this.getSeatNo() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SeatInfo() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SeatInfo(final String orderId, final int seatNo) {
        this.orderId = orderId;
        this.seatNo = seatNo;
    }
}
