// Generated by delombok at Wed Sep 25 21:32:07 CST 2024
package food_delivery.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import edu.fudan.common.entity.Food;

@JsonIgnoreProperties(ignoreUnknown = true)
public class StationFoodStoreInfo {
    private String id;
    private String stationId;
    private String storeName;
    private String telephone;
    private String businessTime;
    private double deliveryFee;
    private List<Food> foodList;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStationId() {
        return this.stationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStoreName() {
        return this.storeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTelephone() {
        return this.telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBusinessTime() {
        return this.businessTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public double getDeliveryFee() {
        return this.deliveryFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Food> getFoodList() {
        return this.foodList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStationId(final String stationId) {
        this.stationId = stationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStoreName(final String storeName) {
        this.storeName = storeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTelephone(final String telephone) {
        this.telephone = telephone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBusinessTime(final String businessTime) {
        this.businessTime = businessTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryFee(final double deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFoodList(final List<Food> foodList) {
        this.foodList = foodList;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StationFoodStoreInfo)) return false;
        final StationFoodStoreInfo other = (StationFoodStoreInfo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getDeliveryFee(), other.getDeliveryFee()) != 0) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$stationId = this.getStationId();
        final java.lang.Object other$stationId = other.getStationId();
        if (this$stationId == null ? other$stationId != null : !this$stationId.equals(other$stationId)) return false;
        final java.lang.Object this$storeName = this.getStoreName();
        final java.lang.Object other$storeName = other.getStoreName();
        if (this$storeName == null ? other$storeName != null : !this$storeName.equals(other$storeName)) return false;
        final java.lang.Object this$telephone = this.getTelephone();
        final java.lang.Object other$telephone = other.getTelephone();
        if (this$telephone == null ? other$telephone != null : !this$telephone.equals(other$telephone)) return false;
        final java.lang.Object this$businessTime = this.getBusinessTime();
        final java.lang.Object other$businessTime = other.getBusinessTime();
        if (this$businessTime == null ? other$businessTime != null : !this$businessTime.equals(other$businessTime)) return false;
        final java.lang.Object this$foodList = this.getFoodList();
        final java.lang.Object other$foodList = other.getFoodList();
        if (this$foodList == null ? other$foodList != null : !this$foodList.equals(other$foodList)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StationFoodStoreInfo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $deliveryFee = java.lang.Double.doubleToLongBits(this.getDeliveryFee());
        result = result * PRIME + (int) ($deliveryFee >>> 32 ^ $deliveryFee);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $stationId = this.getStationId();
        result = result * PRIME + ($stationId == null ? 43 : $stationId.hashCode());
        final java.lang.Object $storeName = this.getStoreName();
        result = result * PRIME + ($storeName == null ? 43 : $storeName.hashCode());
        final java.lang.Object $telephone = this.getTelephone();
        result = result * PRIME + ($telephone == null ? 43 : $telephone.hashCode());
        final java.lang.Object $businessTime = this.getBusinessTime();
        result = result * PRIME + ($businessTime == null ? 43 : $businessTime.hashCode());
        final java.lang.Object $foodList = this.getFoodList();
        result = result * PRIME + ($foodList == null ? 43 : $foodList.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "StationFoodStoreInfo(id=" + this.getId() + ", stationId=" + this.getStationId() + ", storeName=" + this.getStoreName() + ", telephone=" + this.getTelephone() + ", businessTime=" + this.getBusinessTime() + ", deliveryFee=" + this.getDeliveryFee() + ", foodList=" + this.getFoodList() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StationFoodStoreInfo() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StationFoodStoreInfo(final String id, final String stationId, final String storeName, final String telephone, final String businessTime, final double deliveryFee, final List<Food> foodList) {
        this.id = id;
        this.stationId = stationId;
        this.storeName = storeName;
        this.telephone = telephone;
        this.businessTime = businessTime;
        this.deliveryFee = deliveryFee;
        this.foodList = foodList;
    }
}
