// Generated by delombok at Wed Sep 25 21:32:07 CST 2024
package food_delivery.entity;

public class TripOrderInfo {
    private String orderId;
    private String tripId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTripId() {
        return this.tripId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTripId(final String tripId) {
        this.tripId = tripId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TripOrderInfo)) return false;
        final TripOrderInfo other = (TripOrderInfo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$orderId = this.getOrderId();
        final java.lang.Object other$orderId = other.getOrderId();
        if (this$orderId == null ? other$orderId != null : !this$orderId.equals(other$orderId)) return false;
        final java.lang.Object this$tripId = this.getTripId();
        final java.lang.Object other$tripId = other.getTripId();
        if (this$tripId == null ? other$tripId != null : !this$tripId.equals(other$tripId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TripOrderInfo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $orderId = this.getOrderId();
        result = result * PRIME + ($orderId == null ? 43 : $orderId.hashCode());
        final java.lang.Object $tripId = this.getTripId();
        result = result * PRIME + ($tripId == null ? 43 : $tripId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "TripOrderInfo(orderId=" + this.getOrderId() + ", tripId=" + this.getTripId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TripOrderInfo() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TripOrderInfo(final String orderId, final String tripId) {
        this.orderId = orderId;
        this.tripId = tripId;
    }
}
